[project]
name = "pi-value-function"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "openpi",  # main package with the backbone
    "gemma",  # Gemma LLM library
    "jax>=0.4.20",
    "flax>=0.8.0",
    "optax>=0.1.7",
    "numpy>=1.22.4",
    "kagglehub>=0.3.4",  # For downloading Gemma checkpoints
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = ["pytest>=8.3.4"]

[tool.uv.sources]
openpi = { workspace = true }

[tool.ruff]
line-length = 120
target-version = "py310"
